### ISSUE TITLE
Decide on a cloud provider

### ISSUE THREAD

**Issue by rsalmond** [progredo/bootcamp#2]
We need to chose a place to deploy our project. There's plenty of criteria we could consider, features of the provider, cost, usability, etc. I think we should consider prioritizing learning industry standard stuff. it's not gonna do us much good if we all get really comfortable using a cloud provider that nobody's ever heard of, I think we should stick to the big ones as that is most helpful on a resume.

That basically leaves us with these options: GCP, AWS, or Azure.

I'm veto'ing IBM and Oracle and the rest are all tied for last as far as I'm concerned.

**Comment by theplat** [comment]
Agreed with the overall idea that we need to focus on industry standards. 

A thought I had, which may be crazy, is what if we used more than one. like some people churn credit cards, we could churn free tier's and credit pools?

is that even possible? Could we setup terraforms in such a way that you could choose what cloud to deploy onto dynamically?

**Comment by rsalmond** [comment]
It totally is. I think a migration to another cloud provider is a great idea for a real world sort of task, but I was thinking it might be better to tackle that down the road once we're up and stable on one provider to limit the sheer volume of brand new concepts we're introducing at once.

**Comment by theplat** [comment]
make sense to me. I'd say then lets stay with the plan to start on AWS, since we can rotate between free tier accounts in various peoples names in the sort term,

**Comment by chester-tester** [comment]
I agree with @theplat on starting with AWS.

**Comment by wayne868** [comment]
Sorry for the late response guys, Yes i agree we should start on AWS

**Comment by rsalmond** [comment]
👍 consensus: achieved! Closing.
